Premier-League: 9
Championship: 10
League-One: 15
League-Two: 16
National-League: 34
Belgian-Pro-League: 37 
Bundesliga: 20 
2-Bundesliga: 33
La-Liga: 12
Segunda-Division: 17
Ligue-1: 13
Ligue-2: 60
Super-League-Greece: 27
Eredivisie: 23
Serie-A: 11
Serie-B: 18
Primeira-Liga: 32
Scottish-Premiership: 40
Scottish-Championship: 72
Super-Lig: 26