Premier-League: E0
Championship: E1
League-One: E2
League-Two: E3
National-League: EC
Belgian-Pro-League: B1
Bundesliga: D1
2-Bundesliga: D2
La-Liga: SP1
Segunda-Division: SP2
Ligue-1: F1
Ligue-2: F2
Super-League-Greece: G1
Eredivisie: N1
Serie-A: I1
Serie-B: I2
Primeira-Liga: P1
Scottish-Premiership: SC0
Scottish-Championship: SC1
Super-Lig: T1