Premier-League: england
Championship: england2
League-One: england3
League-Two: england4
National-League: england5
Belgian-Pro-League: belgium
Bundesliga: germany
2-Bundesliga: germany2
La-Liga: spain
Segunda-Division: spain2
Ligue-1: france
Ligue-2: france2
Super-League-Greece: greece
Eredivisie: netherlands
Serie-A: italy
Serie-B: italy2
Primeira-Liga: portugal
Scottish-Premiership: scotland
Scottish-Championship: scotland2
Super-Lig: turkey