output_root: data/DATA

jobs:
  - source: football-data
    league: Championship
    seasons:
      - 2425
      - 2324

  - source: football-data
    league: Premier-League
    seasons:
      - 2425
